function menu(){
    var menuhtml = "<div>"
    +"<ul id='nav' >"
    + "<li class='current' style='margin-left: 200px'><a href='principal_tecnico.php'>INICIO</a></li>"
    + "<li><a href='#'>PREINSCRIPCION</a>"
    +" <ul>"
    +"<li><a href=''>PRODUCTOR</a></li>"
    +"<li><a href='../preinscripcion/predio/gestionPredio.php'>PREDIO / LOTE</a></li>"
    +"<li><a href=''>TRAMPA</a></li>"
    +"</ul>"
    +"</li>"
    +"<li><a href='#'>TRABAJO DE CAMPO</a>"
    +"<ul>"
    +"<li><a href='#'>TRAMPEO</a>"
    +"<ul>"
    +"<li><a href=''>RUTA</a></li>"
    +"<li><a href=''>PREDIO</a></li>"
    +"</ul>"
    +"</li>"
    +"<li><a href='#'>CAPTURA</a>"
    +"<ul>"
    +"<li><a href=''>RUTA</a></li>"
    +"<li><a href=''>PREDIO</a></li>"
    +"</ul>"
    +"</li>"
    +"<li><a href='#'>RECOLECCION DE FRUTOS</a>"
    +"<ul>"
    +"<li><a href=''>RUTA</a></li>"
    +"<li><a href='../formatos/mf_fru/gestionMf_fru_p.php'>PREDIO</a></li>"
    +"</ul>"
    +"</li>"
    +"</ul>"
    +"</li>"
    +"<li><a href='contacto.php'>CONTACTO</a></li>"
    +"<li><a href='#'>ACERCA DE</a></li>"
    +"<li><a href='#'>PERFIL</a>"
    +"<ul>"
    +"<li><a href=''>VER PERFIL</a></li>"
    +"<li><a href=''>ACTUALIZAR DATOS</a></li>"
    +"<li><a href=''>CAMBIAR CONTRASEÑA</a></li>"
    +"<li><a href='#' onclick='logout()'>CERRAR SESION</a></li>"
    +"</ul>"
    +"</li>"
    +"<li style='font-size: 20px; color: black; padding-top: 4px; margin-left: 200px'>"
    +"</li>"
    +"<li><a href='#' onclick='logout()'>(SALIR)</a></li>"
    +"</ul>"
    +"</div>"
    $('#menu').append(menuhtml);
}


